[package]
name = "rust-language-practice"
version = "0.1.0"
authors = ["S m, Aruna <aruna.s.m@intel.com>"]

[dependencies]
hyper = "0.12.11"
hyper-tls = "0.3.0"
native-tls = "0.2.1"
serde_json = "1.0"
tokio-core = "0.1.17"
futures = "0.1.24"